//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 01:22:31 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hind.com/elibrary/webservice/soap/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hind.elibrary.webservice.soap.model;
